<?php

declare(strict_types=1);

namespace App\Amqp\Consumer;

use Hyperf\Amqp\Builder\ExchangeBuilder;
use Hyperf\Amqp\Builder\QueueBuilder;
use Hyperf\Amqp\Result;
use Hyperf\Amqp\Annotation\Consumer;
use Hyperf\Amqp\Message\ConsumerMessage;

/**
 * @Consumer(exchange="hyperf", routingKey="hyperf.aaa", queue="hyperf", name ="DemoConsumer", nums=8, enable=false)
 */
class DemoConsumer extends ConsumerMessage
{
    protected $exchange = 'hyperf';

    protected $queue = 'hyperf';

    protected $routingKey = 'hyperf.aaa';

    public function consume($data): string
    {
        echo 'result:' . json_encode($data) . '；time：' . microtime() . PHP_EOL;
        return Result::NACK;
    }

    public function getExchangeBuilder(): ExchangeBuilder
    {
        return parent::getExchangeBuilder()->setDurable(true); // TODO: Change the autogenerated stub
    }

    public function getQueueBuilder(): QueueBuilder
    {
        return parent::getQueueBuilder()->setDurable(true); // TODO: Change the autogenerated stub
    }
}
